name: Deploy in development server
on:
  push:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: auto update via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            ls
            cd /root/dronfiesuss-ades
            git fetch --all
            git reset --hard origin/develop
            npm install
            npm run-script build
            pm2 reload frontend
          host: ${{ secrets.SSH_DEV_HOST }}
          user: root
          pass: ${{ secrets.SSH_DEV_KEY}}
          args: "-tt -vvv"